<a href="https://colab.research.google.com/github/avishank-dwivedi/Pytorch-Framework/blob/main/tensors_in_pytorchipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

what is tensor

tensor is a mathematical object that can be thought of as a generalization of scalars, vectors, and matrices. In the context of machine learning and deep learning, tensors are the fundamentaldata structures used to represent data and parameters.


Scalar: A single number (e.g., 5). This can be considered a 0-dimensional tensor.

Vector: A 1-dimensional array of numbers (e.g., [1, 2, 3]). This is a 1-dimensional tensor.

Matrix: A 2-dimensional array of numbers (e.g., [[1, 2], [3, 4]]). This is a 2-dimensional tensor.

Higher-dimensional tensors: Arrays with more than two dimensions (e.g., a 3D array representing an image with height, width, and color channels).

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"using  GPU{torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")


GPU is available
using  GPUTesla T4


Create a Tensor


In [ ]:

a=torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#usin rand4

torch.rand(2,3)

tensor([[0.5263, 0.9767, 0.2792],
        [0.1332, 0.1519, 0.2049]])

In [ ]:
#using seed
torch.manual_seed(1729)
torch.rand(2,3)


tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])

In [ ]:
#using tensors

torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [ ]:
#arange
print("using arange->", torch.arange(0,10,2))

#using linespace
print("using linespace ->", torch.linspace(0,10,10))

#using eye
print("using eye-> " , torch.eye(5))

# using full
print("using full ->", torch.full((3,3), 5))

using arange-> tensor([0, 2, 4, 6, 8])
using linespace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
# prompt: Tensor shape

x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[   96,    96, 70228],
        [   36,     0,     0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x , dtype=torch.float32)

tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor datatypes

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0] ,dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#using to() to change dtype
x.to()

tensor([[1, 2, 3],
        [4, 5, 6]])

Mathematical Operations


1.scaler operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.6128, 0.1519],
        [0.0453, 0.5035]])

In [ ]:
#addition

x+2

tensor([[2.6128, 2.1519],
        [2.0453, 2.5035]])

In [ ]:
#subbstraction

x-2

tensor([[-1.3872, -1.8481],
        [-1.9547, -1.4965]])

In [ ]:
#multiplication
x*3

tensor([[1.8383, 0.4558],
        [0.1360, 1.5105]])

In [ ]:
#division
x / 3

tensor([[0.2043, 0.0506],
        [0.0151, 0.1678]])

In [ ]:
# int division
(x * 100)//3

tensor([[20.,  5.],
        [ 1., 16.]])

In [ ]:
#mod
((x * 100)//3)%2

tensor([[0., 1.],
        [1., 0.]])

In [ ]:
x**2

tensor([[0.3755, 0.0231],
        [0.0021, 0.2535]])

2.Element wise operations

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [ ]:
print(a)
print(b)

tensor([[0.9978, 0.3884, 0.6929],
        [0.1703, 0.1384, 0.4759]])
tensor([[0.7481, 0.0361, 0.5062],
        [0.8469, 0.2588, 0.2707]])


In [ ]:
# add
a + b

tensor([[1.7459, 0.4245, 1.1991],
        [1.0173, 0.3973, 0.7466]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
c

tensor([ 1, -2,  3, -4])

In [ ]:
d = torch.tensor([1.9 , 2.3 , 4.6 , 6.4])

In [ ]:
#round
torch.round(d)

tensor([2., 2., 5., 6.])

In [ ]:
#ceil
torch.ceil(d)

tensor([2., 3., 5., 7.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 4., 6.])

In [ ]:
#clamp
torch.clamp(d,min=2,max=4)

tensor([2.0000, 2.3000, 4.0000, 4.0000])

3.Reduction Operation

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10)
e

tensor([[2, 1, 3],
        [2, 7, 4]])

In [ ]:
# sum
torch.sum(e)
#sum along columns
torch.sum(e,dim=0)
#sum along rows
torch.sum(e,dim=1)


tensor([ 6, 13])

In [ ]:
 #mean

#mean
torch.mean(e.float()) # Mean requires floating point tensor
torch.mean(e.float(), dim=0)
torch.mean(e.float(), dim=1)

tensor([2.0000, 4.3333])

In [ ]:


#median
torch.median(e.float())
torch.median(e.float(), dim=0)
torch.median(e.float(), dim=1)


torch.return_types.median(
values=tensor([2., 4.]),
indices=tensor([0, 2]))

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(1)

In [ ]:
#product
torch.prod(e)


tensor(336)

In [ ]:
#standard daviation
torch.std(e.float())

tensor(2.1370)

In [ ]:
# variance
torch.var(e.float())

tensor(4.5667)

In [ ]:
#argmax

torch.argmax(e)


tensor(4)

In [ ]:
#argmin
torch.argmin(e)


tensor(1)

4. matrix operations

In [ ]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)

tensor([[9, 0, 7],
        [5, 7, 3]])
tensor([[0, 4],
        [0, 1],
        [9, 8]])


In [ ]:
#matrix multiplication
torch.matmul(f,g)

tensor([[63, 92],
        [27, 51]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
torch.transpose(f,0,1)

tensor([[9, 5],
        [0, 7],
        [7, 3]])

In [ ]:
h = torch.randint(size=(3,3),low=0,high=10 , dtype=torch.float32)

h

tensor([[6., 7., 4.],
        [2., 0., 4.],
        [8., 9., 9.]])

In [ ]:
# determinant
torch.det(h)

tensor(-46.0000)

In [ ]:
#inverse
torch.inverse(h)

tensor([[ 0.7826,  0.5870, -0.6087],
        [-0.3043, -0.4783,  0.3478],
        [-0.3913, -0.0435,  0.3043]])

5.comaprision operation

6.spacial function

In [ ]:
k = torch.randint(size=(2,3),low=0,high=10 , dtype=torch.float32)
k

tensor([[5., 3., 0.],
        [3., 7., 2.]])

In [ ]:
#log
torch.log(k)

tensor([[1.6094, 1.0986,   -inf],
        [1.0986, 1.9459, 0.6931]])

In [ ]:
#exp
torch.exp(k)

tensor([[1.4841e+02, 2.0086e+01, 1.0000e+00],
        [2.0086e+01, 1.0966e+03, 7.3891e+00]])

In [ ]:
#squere root
torch.sqrt(k)

tensor([[2.2361, 1.7321, 0.0000],
        [1.7321, 2.6458, 1.4142]])

In [ ]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9526, 0.5000],
        [0.9526, 0.9991, 0.8808]])

In [ ]:
#softmax
torch.softmax(k,dim=1)

tensor([[0.8756, 0.1185, 0.0059],
        [0.0179, 0.9756, 0.0066]])

In [ ]:
#relu
torch.relu(k)

tensor([[5., 3., 0.],
        [3., 7., 2.]])

Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.8217, 0.2612, 0.7375],
        [0.8328, 0.8444, 0.2941]])
tensor([[0.3788, 0.4567, 0.0649],
        [0.6677, 0.7826, 0.1332]])


In [ ]:
m.add_(n)

tensor([[1.2005, 0.7179, 0.8024],
        [1.5006, 1.6270, 0.4272]])

In [ ]:
m

tensor([[1.2005, 0.7179, 0.8024],
        [1.5006, 1.6270, 0.4272]])

In [ ]:
n

tensor([[0.3788, 0.4567, 0.0649],
        [0.6677, 0.7826, 0.1332]])

In [ ]:
torch.relu(m)

tensor([[1.2005, 0.7179, 0.8024],
        [1.5006, 1.6270, 0.4272]])

Copying a Tensor


In [ ]:
a = torch.rand(2,3)

In [ ]:
a

tensor([[0.0000, 0.4945, 0.3857],
        [0.9883, 0.4762, 0.7242]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.0000, 0.4945, 0.3857],
        [0.9883, 0.4762, 0.7242]])

In [ ]:
a[0][0]=0

In [ ]:
a

tensor([[0.0000, 0.4945, 0.3857],
        [0.9883, 0.4762, 0.7242]])

In [ ]:
id(a)

137828904904528

In [ ]:
id(b)

137828904904528

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.4945, 0.3857],
        [0.9883, 0.4762, 0.7242]])

In [ ]:
b

tensor([[0.0000, 0.4945, 0.3857],
        [0.9883, 0.4762, 0.7242]])

In [ ]:
a[0][0]= 10

In [ ]:
a

tensor([[10.0000,  0.4945,  0.3857],
        [ 0.9883,  0.4762,  0.7242]])

In [ ]:
b

tensor([[0.0000, 0.4945, 0.3857],
        [0.9883, 0.4762, 0.7242]])

In [ ]:
id(a)

137828904904528

In [ ]:
id(b)

137828904889200

Tensor Operation o Gpu

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')