<a href="https://colab.research.google.com/github/avishank-dwivedi/Pytorch-Framework/blob/main/02tensor_on_GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor Operation o Gpu

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"using  GPU{torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is available
using  GPUTesla T4


In [ ]:
device = torch.device('cuda')

In [ ]:
#create in new tensor on gpu
torch.rand((2,3), device= device)

tensor([[0.2648, 0.1482, 0.2457],
        [0.9554, 0.7309, 0.4560]], device='cuda:0')

In [ ]:
#moving an existing tensor gpu
a = torch.rand((2,3))
a.to(device)

tensor([[0.3486, 0.0324, 0.1243],
        [0.3271, 0.2685, 0.0842]], device='cuda:0')

In [ ]:
import time

# Define matrix size
size = 1000

# Create random tensors on CPU
cpu_tensor1 = torch.randn(size, size)
cpu_tensor2 = torch.randn(size, size)

# Perform matrix multiplication on CPU and measure time
start_time = time.time()
cpu_result = torch.matmul(cpu_tensor1, cpu_tensor2)
cpu_time = time.time() - start_time
print(f"Time taken on CPU: {cpu_time:.4f} seconds")

if torch.cuda.is_available():
    # Create random tensors on GPU
    gpu_tensor1 = torch.randn(size, size, device=device)
    gpu_tensor2 = torch.randn(size, size, device=device)

    # Perform matrix multiplication on GPU and measure time
    start_time = time.time()
    gpu_result = torch.matmul(gpu_tensor1, gpu_tensor2)
    # Wait for GPU operations to complete
    torch.cuda.synchronize()
    gpu_time = time.time() - start_time
    print(f"Time taken on GPU: {gpu_time:.4f} seconds")
else:
    print("GPU not available for comparison.")

Time taken on CPU: 0.0173 seconds
Time taken on GPU: 0.0009 seconds


Reshape tensor

In [ ]:
a = torch.ones((2,3))
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#reshape
a.reshape((3,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
#flattin
a.flatten()

tensor([1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand((2,3,4))
b

tensor([[[0.4094, 0.0616, 0.8171, 0.5073],
         [0.8640, 0.3249, 0.0770, 0.0567],
         [0.5611, 0.1319, 0.5465, 0.1287]],

        [[0.2431, 0.4168, 0.5222, 0.3347],
         [0.1135, 0.6158, 0.5896, 0.1203],
         [0.4146, 0.7043, 0.6289, 0.5893]]])

In [ ]:
# permute
b.permute((2,0,1))

tensor([[[0.4094, 0.8640, 0.5611],
         [0.2431, 0.1135, 0.4146]],

        [[0.0616, 0.3249, 0.1319],
         [0.4168, 0.6158, 0.7043]],

        [[0.8171, 0.0770, 0.5465],
         [0.5222, 0.5896, 0.6289]],

        [[0.5073, 0.0567, 0.1287],
         [0.3347, 0.1203, 0.5893]]])

In [ ]:
# unsqueeze
#image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
#squeesze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])