<a href="https://colab.research.google.com/github/avishank-dwivedi/Pytorch-Framework/blob/main/03numpy_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy and pytorch

In [ ]:
import numpy as np

In [ ]:
import torch

In [ ]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b =a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])