<a href="https://colab.research.google.com/github/avishank-dwivedi/Pytorch-Framework/blob/main/05modelBuilding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np
 import pandas as pd
 import torch
 from sklearn.model_selection import train_test_split
 from sklearn.preprocessing import StandardScaler
 from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv("breast-cancer.csv")
df.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [ ]:
df.drop(columns = ["id"],inplace = True)

In [ ]:
df.shape

(569, 31)

In [ ]:
#train test split

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Separate features (x) and target (y)
x = df.iloc[:, 1:]
y = df.iloc[:, 0]




x_train ,x_test ,y_train ,y_test =train_test_split(x,y, test_size=0.2)

In [ ]:
#scaling

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train

array([[ 0.39243633,  1.09164011,  0.49779369, ...,  1.52843382,
         0.1727854 ,  1.16968255],
       [-0.15370121, -1.15027955, -0.17557953, ...,  0.20576949,
         0.11594673, -0.63238398],
       [-0.62872708,  0.52823798, -0.61364301, ..., -0.41852807,
        -0.94504184,  0.79035573],
       ...,
       [ 0.18763475,  1.43529202,  0.12278168, ..., -0.08597247,
        -0.28666054, -0.79246201],
       [-0.53485969, -0.95156926, -0.56501508, ..., -0.90133834,
        -0.38297051, -0.26151013],
       [ 1.76631355, -1.15495509,  1.78767018, ...,  0.71518421,
        -0.85188957, -0.41102195]])

In [ ]:
y_train

509    M
19     B
450    B
471    B
529    B
      ..
424    B
119    M
542    B
324    B
4      M
Name: diagnosis, Length: 455, dtype: object

Labeld Encoder


In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,

numpy array to pytorch tensor


In [ ]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
#Define the model

In [ ]:
class mysimpleNN():
    def __init__(self, x):
        self.weights = torch.rand(x.shape[1], 1, dtype= torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype= torch.float64, requires_grad=True)

    def forward(self, x):
      z = torch.matmul(x, self.weights) + self.bias
      y_pred = torch.sigmoid(z)
      return y_pred

    def loss_function(self, y_pred, y):
        #clamp prediction to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred , epsilon, 1-epsilon)

        #calculate loss
        loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
        return loss

In [ ]:
# important parameter


learnin_rate = 0.1
epochs = 25

training pipeline

In [ ]:
#create model
model = mysimpleNN(x_train_tensor)
#define pass
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(x_train_tensor)


  #loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)


  #backward pass

  loss.backward()

  #update weight and bias
#optimizers
  with torch.no_grad():
     model.weights -=learnin_rate * model.weights.grad
     model.bias -= learnin_rate * model.bias.grad

  #zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  #perameter update
  print(f"epoch {epoch+1}: loss = {loss.item()}")





epoch 1: loss = 3.6947131231770487
epoch 2: loss = 3.570868906472261
epoch 3: loss = 3.436420934090917
epoch 4: loss = 3.297583870860833
epoch 5: loss = 3.1559908772145175
epoch 6: loss = 3.0079946464883127
epoch 7: loss = 2.857114966778669
epoch 8: loss = 2.699189814502565
epoch 9: loss = 2.5377956255427665
epoch 10: loss = 2.376033040184973
epoch 11: loss = 2.212977810874909
epoch 12: loss = 2.0529464840526512
epoch 13: loss = 1.8936417245541295
epoch 14: loss = 1.7402802066976943
epoch 15: loss = 1.5963908323252842
epoch 16: loss = 1.4611770570478129
epoch 17: loss = 1.3283923295078612
epoch 18: loss = 1.210533337262913
epoch 19: loss = 1.1088906118678157
epoch 20: loss = 1.0242095891825491
epoch 21: loss = 0.956403062161031
epoch 22: loss = 0.9043313586978804
epoch 23: loss = 0.865831053185543
epoch 24: loss = 0.8380785469916066
epoch 25: loss = 0.8181571112369028


In [ ]:
model.bias

tensor([-0.1177], dtype=torch.float64, requires_grad=True)

model evaluation

In [ ]:
#model evaluate
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred>0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"accuracy = {accuracy.item()}")


accuracy = 0.6637426614761353
